version: "2"

services:      
  db:
    image: mariadb:12.2@sha256:b1cb255a9939d28a1856815f0de6046c20c28c21b92a9f2696bc782b247a47ee
    restart: always
    ports:
      - 3306:3306
    # volumes:
    #   - ./docker-persistence/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev123
      - MYSQL_DATABASE=temp_db

  adminer:
    image: adminer@sha256:2fb88b98da9f0ae0157d8fcb73f447a0747b09ee8d2ff8a8e0695b30afed2116
    depends_on:
      - db
    ports:
      - 8000:8080
  
  spring:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      # required arguments
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/temp_db
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev123
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.mariadb.jdbc.Driver
      # optional arguments
      # - SERVER_PORT=8090
      # - DEBUG=true
      # - SPRING_THYMELEAF_CACHE=false
      # - LOGGING_LEVEL_WEB=DEBUG
    # network_mode: host
    ports: 
      - 8080:8080
