version: "2"

services:      
  db:
    image: mariadb:12.1@sha256:f54db0cb3ccfe9431aba6d08c65a1763c499789b116b4cb651dd7fcf325965b3
    restart: always
    ports:
      - 3306:3306
    # volumes:
    #   - ./docker-persistence/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev123
      - MYSQL_DATABASE=temp_db

  adminer:
    image: adminer@sha256:b6d3c299d1754368031415e567609d500a4a5a22c17b7812749a8f677d93f066
    depends_on:
      - db
    ports:
      - 8000:8080
  
  spring:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      # required arguments
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/temp_db
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev123
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.mariadb.jdbc.Driver
      # optional arguments
      # - SERVER_PORT=8090
      # - DEBUG=true
      # - SPRING_THYMELEAF_CACHE=false
      # - LOGGING_LEVEL_WEB=DEBUG
    # network_mode: host
    ports: 
      - 8080:8080
